### ISSUE TITLE
Setting an action to the button rectangle crashes the app!

### ISSUE THREAD

**Issue by MelodyAustin** [navasmdc/MaterialDesignLibrary#104]
I have just directly copied the button from your code and replaced a button on my app with it with the button id. But now the app crashes, please let me know what needs to be done..

**Comment by Inoy1st** [comment]
If you want to get any help on error - paste your *error message*

**Comment by MelodyAustin** [comment]
I don't get an error, the app would just crash on the device. The button works when nothing is set for it to do, but when I set an action to it and run it on device, the app would just  crash..

**Comment by navasmdc** [comment]
Hi, Can you paste your stacktrace error?

**Comment by MelodyAustin** [comment]
Hello these are the errors in my Logcat 

<b> java.lang.RuntimeException: Unable to start activity ComponentInfo{infinitetech.chemequator/infinitetech.chemequator.MainActivity}: java.lang.ClassCastException: com.gc.materialdesign.views.ButtonRectangle cannot be cast to android.widget.Button </b>
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5096)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
<b>     Caused by: java.lang.ClassCastException: com.gc.materialdesign.views.ButtonRectangle cannot be cast to android.widget.Button </b>
            at infinitetech.chemequator.MainActivity.defaultops(MainActivity.java:56)
            at infinitetech.chemequator.MainActivity.onCreate(MainActivity.java:44)
            at android.app.Activity.performCreate(Activity.java:5244)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2225)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5096)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by MelodyAustin** [comment]
Sorry I figured it out :P Had to import the view and then set the button to com....Button rectangle instead of the usual Button.
Thank you for taking your time

**Comment by Inoy1st** [comment]
I was believing in you :)


*P.S.: if there is no error now, you can close issue*
