### ISSUE TITLE
Button Float NoClassDefFoundError

### ISSUE THREAD

**Issue by arafeh94** [navasmdc/MaterialDesignLibrary#106]
I get this error when i use button float in the last version of the library 
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/view/ViewHelper;
            at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:113)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5223)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.view.ViewHelper" on path: DexPathList[[zip file "/data/app/com.it.university.lbu-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:113)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5223)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
    Suppressed: java.lang.ClassNotFoundException: com.nineoldandroids.view.ViewHelper
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by navasmdc** [comment]
Hi friend, How have you imported the library?

**Comment by arafeh94** [comment]
yes i use android studio gradle and I add the source to find the bug;
the error is where you use ViewHelper error that there is no ViewHelper class in the application

**Comment by conzorz** [comment]
Same here...

**Comment by samskiter** [comment]
same here in Slider.java

**Comment by martyglaubitz** [comment]
i'm also affected, makes the Widget unusable :(

**Comment by samskiter** [comment]
I checked out the repo and removed a bunch of stuff from the gradle file to get it working

**Comment by afermin** [comment]
HI, same here. You could solve the problem?

**Comment by chackor** [comment]
samskiter - can you describe what you did?

**Comment by kevinkl** [comment]
Hi have the same problem with the ButtonFloat. This is the error.
java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper
            at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:108)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

@samskiter how did you fix this problem?

**Comment by flymanj** [comment]
ok, I had the same issue
I needed to add that dependancy too 
compile 'com.nineoldandroids:library:2.4.+'

**Comment by newbyca** [comment]
Hi there. I had same issue. Adding:
compile 'com.nineoldandroids:library:2.4.+'
to app gradle dependencies fixed for me too.

**Comment by kevinkl** [comment]
It works fine with that dependency. Thank you guys!

**Comment by luisreyes** [comment]
This should be added to the README...

**Comment by develth** [comment]
+1 for adding to README

**Comment by zwickers** [comment]
Huh, I was having this same exact error. Adding:
compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
fixed it for me also. Thanks for the fix, flymanj!
