### ISSUE TITLE
NullPointerException on Slider's invalidate() method

### ISSUE THREAD

**Issue by itsalltoomuch** [navasmdc/MaterialDesignLibrary#128]
I face this problem when running the app on old android device ( api level <11 )

Caused by: java.lang.NullPointerException
            at com.gc.materialdesign.views.Slider.invalidate(Slider.java:97)
            at android.view.View.setBackgroundDrawable(View.java:7626)
            at android.view.View.<init>(View.java:2160)
            at android.view.View.<init>(View.java:1899)
            at android.view.ViewGroup.<init>(ViewGroup.java:286)
            at android.widget.RelativeLayout.<init>(RelativeLayout.java:173)
            at com.gc.materialdesign.views.CustomView.<init>(CustomView.java:21)
            at com.gc.materialdesign.views.Slider.<init>(Slider.java:48)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
            at android.view.LayoutInflater.createView(LayoutInflater.java:505)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:276)

**Comment by djpeinado** [comment]
I also faced it with Checkbox running app on api 10

     Caused by: java.lang.NullPointerException
            at com.gc.materialdesign.views.CheckBox.invalidate(CheckBox.java:83)
            at android.view.View.setBackgroundDrawable(View.java:7626)
            at android.view.View.<init>(View.java:2160)
            at android.view.View.<init>(View.java:1899)
            at android.view.ViewGroup.<init>(ViewGroup.java:286)
            at android.widget.RelativeLayout.<init>(RelativeLayout.java:173)
            at com.gc.materialdesign.views.CustomView.<init>(CustomView.java:22)
            at com.gc.materialdesign.views.CheckBox.<init>(CheckBox.java:32)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
            at android.view.LayoutInflater.createView(LayoutInflater.java:505)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.customView(MaterialDialog.java:1285)
            at com.geoslab.fidelity.Utils.login(Utils.java:56)
            at com.geoslab.fidelity.activity.MainActivity$2.onClick(MainActivity.java:93)
            at android.view.View.performClick(View.java:2485)
            at android.view.View$PerformClick.run(View.java:9080)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jmvines** [comment]
Like me the same problem #162
