### ISSUE TITLE
java.lang.IllegalArgumentException when setting visibility of ProgressBarCircularIndeterminate

### ISSUE THREAD

**Issue by rajohns08** [navasmdc/MaterialDesignLibrary#143]
The following exception can be reproduced with a github example at: https://github.com/rajohns08/MaterialLibraryBug

java.lang.IllegalArgumentException: width and height must be > 0
            at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:674)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:641)
            at com.gc.materialdesign.views.ProgressBarCircularIndeterminate.drawFirstAnimation(ProgressBarCircularIndeterminate.java:96)
            at com.gc.materialdesign.views.ProgressBarCircularIndeterminate.onDraw(ProgressBarCircularIndeterminate.java:73)
            at android.view.View.draw(View.java:13944)
            at android.view.View.getDisplayList(View.java:12838)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
            at android.view.View.getDisplayList(View.java:12775)
            at android.view.View.getDisplayList(View.java:12880)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2367)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2239)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mntgoat** [comment]
I just had the same issue, any workarounds?

**Comment by djokobozinov** [comment]
Thats beacous you switch from GONE to VISIBLE, instead of that try to switch from INVISIBLE to VISIBLE

**Comment by Zane-cqupt** [comment]
Thank u!  It works for me!
