### ISSUE TITLE
Dialog error when finishing activity

### ISSUE THREAD

**Issue by r4phab** [navasmdc/MaterialDesignLibrary#152]
Log error when finish current activity on AcceptButton event.

Error :
E/WindowManager﹕ android.view.WindowLeaked: Activity <MYACTIVITY> has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4264e6f0 V.E..... R......D 0,0-1080,1920} that was originally added here...

My code : 
dialog.setOnAcceptButtonClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        //content
                        dialog.dismiss();
                        finish();
                    }
                });

```
            dialog.show();
```

Trying with the stock dialog and no error appears.

**Comment by shirish87** [comment]
I just ran into this issue.

It occurs because calling [`snackbar.dismiss()`](https://github.com/navasmdc/MaterialDesignLibrary/blob/master/MaterialDesign/src/com/gc/materialdesign/widgets/SnackBar.java#L131) schedules an animation which calls its parent's `dialog.dismiss()` after it finishes. By the time the animation is complete, the activity has already been destroyed.

The issue can also be reproduced by creating and showing a SnackBar and changing the phone's orientation.

We need a way to skip the animation during `snackbar.dismiss()`. Something like:

    public void dismiss(boolean useAnimation) {
        if (!useAnimation) {
            super.dismiss();
            return;
        }

        Animation anim = AnimationUtils.loadAnimation(activity, R.anim.snackbar_hide_animation);
        anim.setAnimationListener(new AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {
            }

            @Override
            public void onAnimationRepeat(Animation animation) {
            }

            @Override
            public void onAnimationEnd(Animation animation) {
                SnackBar2.super.dismiss();
            }
        });
        view.startAnimation(anim);
    }

Stacktrace for issue:

      02-20 10:20:52.576  17913-17913/com.buggycoder.android.f E/WindowManager﹕ android.view.WindowLeaked: Activity com.buggycoder.android.f.ui.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41b3c2c0 V.E..... R......D 0,0-480,782} that was originally added here
                  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                  at android.app.Dialog.show(Dialog.java:286)
                  at com.gc.materialdesign.widgets.SnackBar.show(SnackBar.java:93)
                  at com.buggycoder.android.f.ui.MainActivity.onCreate(MainActivity.java:86)
                  at android.app.Activity.performCreate(Activity.java:5283)
                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                  at android.app.ActivityThread.access$800(ActivityThread.java:135)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:136)
                  at android.app.ActivityThread.main(ActivityThread.java:5001)
                  at java.lang.reflect.Method.invokeNative(Native Method)
                  at java.lang.reflect.Method.invoke(Method.java:515)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                  at dalvik.system.NativeStart.main(Native Method)
