### ISSUE TITLE
Android Studio Preview Error

### ISSUE THREAD

**Issue by hanc1208** [navasmdc/MaterialDesignLibrary#163]
i got error in preview window while i am writing xml.

 <com.gc.materialdesign.views.ButtonRectangle
                android:layout_width="113dp"
                android:layout_height="45dp"
                android:text="OK"/>

java.lang.NoSuchFieldError: shape_bacground
	at com.gc.materialdesign.views.Button.setBackgroundColor(Button.java:166)
	at com.gc.materialdesign.views.Button.setDefaultProperties(Button.java:50)
	at com.gc.materialdesign.views.ButtonRectangle.setDefaultProperties(ButtonRectangle.java:35)
	at com.gc.materialdesign.views.Button.<init>(Button.java:36)
	at com.gc.materialdesign.views.ButtonRectangle.<init>(ButtonRectangle.java:23)

**Comment by CookieMaster** [comment]
Hmm well first it seems like you spelt "shape_bacground " incorrectly. Should be "shape_background

This could be the cause of the other errors.

**Comment by hanc1208** [comment]
I haven't never made the drawable named "shape_bacground". I found "shape_bacground" in the library. (Button.java:166)

**Comment by CookieMaster** [comment]
Hmm, can you add a picture of the error that comes from the console.

**Comment by hanc1208** [comment]
![image](https://cloud.githubusercontent.com/assets/6322585/6430503/b688f3e0-c04f-11e4-9c65-337d27976ec3.png)

            <com.gc.materialdesign.views.ProgressBarDeterminate
                android:layout_width="match_parent"
                android:layout_height="wrap_content"


                android:background="@color/primary"
                android:progress="10"/>

**Comment by hadidez** [comment]
same issue
