### ISSUE TITLE
ArrayIndexOutOfBoundsException in com.gc.materialdesign.views.ProgressBarIndeterminate$1$1.onAnimationEnd

### ISSUE THREAD

**Issue by kenyee** [navasmdc/MaterialDesignLibrary#180]
Didn't see this in the list of issues so I thought I'd log it...

03-03 13:02:48.114    9761-9849/com.mustbin.mustbin D/com.mustbin.mustbin.s3.S3Downloader﹕ Forbidden from reading 20E5709B-4F2A-4E93-A95A-20A62BE72481 in mb_docs_stage
03-03 13:02:48.514    9761-9761/com.mustbin.mustbin D/dalvikvm﹕ GC_FOR_ALLOC freed 8139K, 28% free 73873K/102420K, paused 19ms, total 20ms
03-03 13:02:52.062    9761-9761/com.mustbin.mustbin D/AndroidRuntime﹕ Shutting down VM
03-03 13:02:52.062    9761-9761/com.mustbin.mustbin W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xa4ca5b20)
03-03 13:02:52.066    9761-9761/com.mustbin.mustbin E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mustbin.mustbin, PID: 9761
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.nineoldandroids.animation.KeyframeSet.ofFloat(KeyframeSet.java:77)
            at com.nineoldandroids.animation.PropertyValuesHolder.setFloatValues(PropertyValuesHolder.java:328)
            at com.nineoldandroids.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setFloatValues(PropertyValuesHolder.java:932)
            at com.nineoldandroids.animation.PropertyValuesHolder$FloatPropertyValuesHolder.<init>(PropertyValuesHolder.java:919)
            at com.nineoldandroids.animation.PropertyValuesHolder.ofFloat(PropertyValuesHolder.java:176)
            at com.nineoldandroids.animation.ObjectAnimator.setFloatValues(ObjectAnimator.java:351)
            at com.nineoldandroids.animation.ObjectAnimator.ofFloat(ObjectAnimator.java:232)
            at com.gc.materialdesign.views.ProgressBarIndeterminate$1$1.onAnimationEnd(ProgressBarIndeterminate.java:39)
            at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
            at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
            at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
03-03 13:03:02.834    9761-9824/com.mustbin.mustbin D/skia﹕ --- SkImageDecoder::Factory returned null
03-03 13:03:02.834    9761-9824/com.mustbin.mustbin D/skia﹕ --- SkImageDecoder::Factory returned null
03-03 13:03:02.834    9761-9824/com.mustbin.mustbin I/com.mustbin.mustbin.s3.S3Manager﹕ Cache lookup for 265.jpg
03-03 13:03:02.834    9761-9824/com.mustbin.mustbin D/com.mustbin.mustbin.s3.S3Downloader﹕ Downloading 265.j

**Comment by navasmdc** [comment]
Hi, sorry but this error is of the nineolds library. Does this error happen always?

**Comment by kenyee** [comment]
happens occasionally

**Comment by kenyee** [comment]
any idea when you'll issue another release of the library to jcenter?  Happens far too often in our app now :-(
