### ISSUE TITLE
NullPointerException in ButtonRectangle.onDraw

### ISSUE THREAD

**Issue by sohayb** [navasmdc/MaterialDesignLibrary#223]
Hello,
I have a NPE reported from a Sony LT22i device with Android 4.0.4, this is the full stack trace:

```
java.lang.NullPointerException
       at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
       at com.gc.materialdesign.views.ButtonRectangle.onDraw(SourceFile:128)
       at android.view.View.draw(View.java:11108)
       at android.view.View.getDisplayList(View.java:10547)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2704)
       at android.view.View.getDisplayList(View.java:10510)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:842)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:1914)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1638)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2446)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4448)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Any idea?

**Comment by bkraszewski** [comment]
@sohayb do you still have this error after updating to 1.5?

**Comment by sohayb** [comment]
@bkraszewski No, didn't face it yet. Hopefully it won't happen anymore.

**Comment by Pantsu-It** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
