### ISSUE TITLE
circular

### ISSUE THREAD

**Issue by ajay67** [navasmdc/MaterialDesignLibrary#244]

**Comment by navasmdc** [comment]
Hi, you can try this code:

ProgressDialog progressDialog = new ProgressDialog(WidgetActivity.this, "Loading");
						progressDialog.show();

**Comment by jam01** [comment]
Keep getting NPE:

Caused by: java.lang.NullPointerException
            at com.gc.materialdesign.widgets.ProgressDialog.onCreate(ProgressDialog.java:50)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
            at android.app.Dialog.show(Dialog.java:262)
            at com.gc.materialdesign.widgets.ProgressDialog.show(ProgressDialog.java:77)
            at com.jam01.littlelight.MainActivity.onCreate(MainActivity.java:32)

**Comment by ajay67** [comment]
Thanks Ivan. Its working.

But size of the text ("Loading") looks big. Can I modify it?

**Comment by ajay67** [comment]
I tried to change text size by following but getting java.lang.NullPointerException

progressDialog.getTitleTextView().setTextSize(10);
