### ISSUE TITLE
Crash com.gc.materialdesign.views.Switch

### ISSUE THREAD

**Issue by sphairo** [navasmdc/MaterialDesignLibrary#270]
Process: mx.sphairo.systems, PID: 27740
    java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper
            at com.gc.materialdesign.views.Switch.placeBall(Switch.java:178)
            at com.gc.materialdesign.views.Switch.onDraw(Switch.java:125)

**Comment by JDNew** [comment]
You can try to add " compile 'com.nineoldandroids:library:2.4.+' ".It might work for you.

**Comment by JDNew** [comment]
@sphairo   You can try to add " compile 'com.nineoldandroids:library:2.4.+' ".It might work for you.
