### ISSUE TITLE
com.gc.materialdesign.views.Slider

### ISSUE THREAD

**Issue by sphairo** [navasmdc/MaterialDesignLibrary#271]
java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper
            at com.gc.materialdesign.views.Slider.placeBall(Slider.java:231)
            at com.gc.materialdesign.views.Slider.onDraw(Slider.java:106)

**Comment by shanmukhateja** [comment]
add compile 'com.nineoldandroids:library:2.4.0+' line to the dependencies block of gradle script and resync.
