### ISSUE TITLE
get NullPointerException on button.setText()

### ISSUE THREAD

**Issue by rorlig** [navasmdc/MaterialDesignLibrary#278]
Hi I keep getting NPE when trying to change the text of button in the layout. The button reference is not null. 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
            at com.gc.materialdesign.views.Button.setText(Button.java:185)
            at com.rorlig.babylog.ui.fragment.feed.NursingFeedFragment.startButtonClicked(NursingFeedFragment.java:160)
            at com.rorlig.babylog.ui.fragment.feed.NursingFeedFragment$$ViewInjector$1.onClick(NursingFeedFragment$$ViewInjector.java:20)
            at com.gc.materialdesign.views.Button.makeCircle(Button.java:135)
            at com.gc.materialdesign.views.ButtonRectangle.onDraw(ButtonRectangle.java:145)
            at android.view.View.draw(View.java:15114)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$Callba

**Comment by AlanVerbner** [comment]
@rorlig Based on the stack I guess you are having this problem with ButtonRectangle which is related to https://github.com/navasmdc/MaterialDesignLibrary/issues/261

**Comment by Anearion** [comment]
I'm having this problem with ButtonRectangle and setText() too, anyone found a solution coding side ?

**Comment by Zapnologica** [comment]
I am also getting this issue, I cant seem to see why.
