### ISSUE TITLE
NullPointerException with ButtonFloat when clicked.

### ISSUE THREAD

**Issue by larrytech7** [navasmdc/MaterialDesignLibrary#329]
I use the button as part of my adapter view for every item in my list. When the first is clicked i get the following stack trace after the animation:

8-21 18:54:12.998  20436-20436/mobile.taverna.apache.org.tavernamobile W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41e02930)
08-21 18:54:13.014  20436-20436/mobile.taverna.apache.org.tavernamobile E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2908)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
            at android.view.View.getDisplayList(View.java:12603)
            at android.view.View.getDisplayList(View.java:12709)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2249)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2121)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1912)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4462)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5106)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by larrytech7** [comment]
This issue is solved by setting the materialdesign:animate="false" property like this. However, i don't think it helps for the interaction and experienced desired with a value of 'true' for this button. Hope there is a quick fix to this soon.
