### ISSUE TITLE
Always appear NullPointerException!

### ISSUE THREAD

**Issue by merhong2012** [navasmdc/MaterialDesignLibrary#330]
No matter yesterday，but today ,when I call the mothed of .show  occurs NullPointerException.
code:
 public void showDialog(Context context, String text) {
        Dialog dialog = new Dialog(context, "Tip", text);
        dialog.setCancelable(false);
        dialog.setCanceledOnTouchOutside(false);
        dialog.setOnAcceptButtonClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
            }
        });
        dialog.show();
    }
      
the error:

 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.gc.materialdesign.widgets.Dialog.onCreate(Dialog.java:62)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:355)
            at android.app.Dialog.show(Dialog.java:260)
            at com.gc.materialdesign.widgets.Dialog.show(Dialog.java:111)
            at cn.cyapp.navyblue.base.BaseActivity.showDialog(BaseActivity.java:312)
            at cn.cyapp.navyblue.ui.LoginActivity.onClick(LoginActivity.java:82)
            at android.view.View.performClick(View.java:4204)
            at android.view.View$PerformClick.run(View.java:17355)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by djokobozinov** [comment]
Don't place dialog.show inside the event listener
Here example to try
 Dialog dialog = new Dialog(mContext, "title","message");
 dialog.show();
 ButtonFlat acceptButton = dialog.getButtonAccept();
 acceptButton.setText("ACCEPT");

**Comment by GreaseMonk** [comment]
He didn't put it inside the event listener
I have the same issue with just the following code that is placed in onStart() of a fragment.

<code>
Dialog dialog = new Dialog(v.getContext(), "Title", "Msg");
dialog.show();
</code>
