### ISSUE TITLE
Fatal error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/view/ViewHelper;

### ISSUE THREAD

**Issue by Informatheus** [navasmdc/MaterialDesignLibrary#381]
## When i try to use this lib I get this:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.informatheus.quantoporlitro, PID: 7059
                                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/view/ViewHelper;
                                                                                   at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:111)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.view.ViewHelper" on path: DexPathList[[dex file "/data/data/com.informatheus.quantoporlitro/files/instant-run/dex/slice-support-annotations-23.3.0_ebf31ba6a53a34df7d3dac487bc345dd7dd9e309-classes.dex"

**_What should I do?_**

**Comment by mlortizrojas** [comment]
same error here.

**Comment by blitzk01** [comment]
same...

**Comment by FarzadJM** [comment]
Add com.nineoldandroids:library:2.4.0 to your dependencies

**Comment by andinirachm** [comment]
Have you try to unactive instant run? I tried and it solved
