### ISSUE TITLE
When I use the Switch 

### ISSUE THREAD

**Issue by furuiCQ** [navasmdc/MaterialDesignLibrary#383]
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.nineoldandroids.view.ViewHelper
            at com.gc.materialdesign.views.Switch.placeBall(Switch.java:178)
            at com.gc.materialdesign.views.Switch.onDraw(Switch.java:125)
            at android.view.View.draw(View.java:13458)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.draw(View.java:13461)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.draw(View.java:13461)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2183)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2147)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2019)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1830)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:525)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by hHui056** [comment]
you need import "com.nineoldandroids" in your buird.gradle,like this ` compile 'com.nineoldandroids:library:2.4.0'`
