### ISSUE TITLE
An error occurred when I used ButtonFloat

### ISSUE THREAD

**Issue by CelineDeer** [navasmdc/MaterialDesignLibrary#407]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/view/ViewHelper;
                                                       at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:111)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5701)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.view.ViewHelper" on path: DexPathList[[zip file "/data/app/huangxl.mdfirstday-2/base.apk"],nativeLibraryDirectories=[/data/app/huangxl.mdfirstday-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at com.gc.materialdesign.views.ButtonFloat$1.run(ButtonFloat.java:111) 
                                                       at android.os.Handler.handleCallback(Handler.java:815) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                       at android.os.Looper.loop(Looper.java:207) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5701) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by CelineDeer** [comment]
didn't find ViewHelper.java in jar

**Comment by CelineDeer** [comment]
I hava solved this problem by adding ( compile 'com.nineoldandroids:library:2.4.0') to dependencies

**Comment by tkdals1119** [comment]
thanks! I solved that problem by adding compile 'com.nineoldandroids:library:2.4.0'
